name: s3-deploys

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: yarn install && yarn run build
        env:
          CI: false

      - name: Deploy app build Fire PokeStore
        run: aws s3 sync ./build/ s3://firepokestore --delete

      - name: Deploy app build Eletric PokeStore
        run: aws s3 sync ./build/ s3://eletricpokestore --delete

      - name: Deploy app build Ghost PokeStore
        run: aws s3 sync ./build/ s3://ghostpokestore --delete

      - name: Deploy app build Water PokeStore
        run: aws s3 sync ./build/ s3://waterpokestore --delete

      - name: Deploy app build Grass PokeStore
        run: aws s3 sync ./build/ s3://grasspokestore --delete
